### ISSUE TITLE
make check fails on gingerbase tarball (CentOS 7.2)

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/gingerbase#151]
[root@localhost ginger-base-2.2.1]# make check 
make  check-recursive
make[1]: Entering directory `/root/ginger-base-2.2.1'
Making check in contrib
make[2]: Entering directory `/root/ginger-base-2.2.1/contrib'
make  check-recursive
make[3]: Entering directory `/root/ginger-base-2.2.1/contrib'
Making check in DEBIAN
make[4]: Entering directory `/root/ginger-base-2.2.1/contrib/DEBIAN'
make[4]: Nothing to be done for `check'.
make[4]: Leaving directory `/root/ginger-base-2.2.1/contrib/DEBIAN'
make[4]: Entering directory `/root/ginger-base-2.2.1/contrib'
make[4]: Nothing to be done for `check-am'.
make[4]: Leaving directory `/root/ginger-base-2.2.1/contrib'
make[3]: Leaving directory `/root/ginger-base-2.2.1/contrib'
make[2]: Leaving directory `/root/ginger-base-2.2.1/contrib'
Making check in control
make[2]: Entering directory `/root/ginger-base-2.2.1/control'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/root/ginger-base-2.2.1/control'
Making check in docs
make[2]: Entering directory `/root/ginger-base-2.2.1/docs'
make[2]: Nothing to be done for `check'.
make[2]: Leaving directory `/root/ginger-base-2.2.1/docs'
Making check in model
make[2]: Entering directory `/root/ginger-base-2.2.1/model'
make  check-am
make[3]: Entering directory `/root/ginger-base-2.2.1/model'
make[3]: Nothing to be done for `check-am'.
make[3]: Leaving directory `/root/ginger-base-2.2.1/model'
make[2]: Leaving directory `/root/ginger-base-2.2.1/model'
Making check in po
make[2]: Entering directory `/root/ginger-base-2.2.1/po'
make[2]: Leaving directory `/root/ginger-base-2.2.1/po'
Making check in tests
make[2]: Entering directory `/root/ginger-base-2.2.1/tests'
make  check-am
make[3]: Entering directory `/root/ginger-base-2.2.1/tests'
make  check-local
make[4]: Entering directory `/root/ginger-base-2.2.1/tests'
./run_tests.sh
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_model.py", line 31, in <module>
    from wok.plugins.gingerbase.model import model
ImportError: No module named gingerbase.model
make[4]: *** [check-local] Error 1
make[4]: Leaving directory `/root/ginger-base-2.2.1/tests'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/root/ginger-base-2.2.1/tests'
make[2]: *** [check] Error 2
make[2]: Leaving directory `/root/ginger-base-2.2.1/tests'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/root/ginger-base-2.2.1'
make: *** [check] Error 2

**Comment by danielhb** [comment]
Have you build the project before running make check? 

This is the full command I use to verify contributions. Please execute it and let me know if the error still occurs:

```
sudo make clean ; sudo ./autogen.sh --system ; sudo make ; sudo make -C ui/css css ; sudo make check
```

**Comment by biancafc** [comment]
I've tried to execute those commands but still getting errors on Fedora 25:

```
$ sudo make check
make  check-recursive
make[1]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1'
Making check in contrib
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
make  check-recursive
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
Making check in DEBIAN
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib/DEBIAN'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib/DEBIAN'
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/contrib'
Making check in control
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/control'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/control'
Making check in docs
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/docs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/docs'
Making check in model
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/model'
make  check-am
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/model'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/model'
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/model'
Making check in po
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/po'
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/po'
Making check in tests
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
make  check-am
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
make  check-local
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
./run_tests.sh
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_authorization.py", line 26, in <module>
    from tests.utils import get_free_port, patch_auth, request, run_server
ImportError: No module named tests.utils
Makefile:493: recipe for target 'check-local' failed
make[4]: *** [check-local] Error 1
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
Makefile:365: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
Makefile:367: recipe for target 'check' failed
make[2]: *** [check] Error 2
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1/tests'
Makefile:605: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/ginger-base-2.2.1'
Makefile:895: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by alinefm** [comment]
Hi @ramonmedeiros and @biancafc 

Have you downloaded and installed ginger directory under wok file structure? ie, under wok/src/wok/plugins ?

You can not run make-check of a plugin without wok. So my recommendation is to download wok tarball, extract it and under wok/src/wok/plugins extract the ginger tarball, and then build everything (wok + ginger) and run make-check.

**Comment by biancafc** [comment]
@alinefm still getting the same problem, I've downloaded wok and gingerbase tar, installed under plugins dir but it still showing me the same errors when I run make check.
