### ISSUE TITLE
ImportError: No module named ethtool when running 'make check' on Fedora 25

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/gingerbase#154]
```
$ sudo make check
make  check-recursive
make[1]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase'
Making check in contrib
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
make  check-recursive
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
Making check in DEBIAN
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib/DEBIAN'
make[4]: Nothing to be done for 'check'.
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib/DEBIAN'
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/contrib'
Making check in control
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/control'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/control'
Making check in docs
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/docs'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/docs'
Making check in model
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/model'
make  check-am
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/model'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/model'
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/model'
Making check in po
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/po'
/usr/bin/msgmerge --update  --lang=en_US en_US.po gingerbase.pot
............................. feito.
/usr/bin/msgmerge --update  --lang=de_DE de_DE.po gingerbase.pot
............................. feito.
/usr/bin/msgmerge --update  --lang=es_ES es_ES.po gingerbase.pot
............................. feito.
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/po'
Making check in tests
make[2]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
make  check-am
make[3]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
make  check-local
make[4]: Entering directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
./run_tests.sh
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "test_netinfo.py", line 25, in <module>
    import wok.plugins.gingerbase.netinfo as netinfo
  File "/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/netinfo.py", line 24, in <module>
    import ethtool
ImportError: No module named ethtool
Makefile:493: recipe for target 'check-local' failed
make[4]: *** [check-local] Error 1
make[4]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
Makefile:365: recipe for target 'check-am' failed
make[3]: *** [check-am] Error 2
make[3]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
Makefile:367: recipe for target 'check' failed
make[2]: *** [check] Error 2
make[2]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase/tests'
Makefile:605: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/bianca/Documentos/kimchi-release-tests/wok/src/wok/plugins/gingerbase'
Makefile:895: recipe for target 'check' failed
make: *** [check] Error 2
```

**Comment by lcorreia** [comment]
Hi Bianca, it seems a dependency is missing to be installed.

**Comment by alinefm** [comment]
Hi @biancafc 
You need to install python-ethtool. If it is not listed in the README dependencies it is a doc issue.
Otherwise, just install it and we can close this issue.

**Comment by biancafc** [comment]
That's true, I've tested again and it worked, closing this issue.
