### ISSUE TITLE
Nothing under Host/Dashboard Tab

### ISSUE THREAD

**Issue by RhymeInspectah** [kimchi-project/gingerbase#175]
Compilation and install of gingerbase and ginger plugins went well, I think. But I've nothing under host/dashboard tab in wokd interface. Under the host/upgrade tab there are upgrades. However, under wok/settings/plugins management tab there are kimchi, gingerbase and ginger active. 
In CLI after wokd launching I've lot of python errors:

rc: 3 error: Redirecting to /bin/systemctl status nginx.service
 returned from cmd: service nginx status
Redirecting to /bin/systemctl start nginx.service
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/cherrypy/process/plugins.py", line 517,                                                                                                              in run
Exception in thread Thread-4:
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/wok/plugins/gingerbase/model/host.py",                                                                                                              line 433, in update_host_stats
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self._get_host_disk_io_rate(seconds)
  File "/usr/lib/python3.8/site-packages/wok/plugins/gingerbase/model/host.py",                                                                                                              line 474, in _get_host_disk_io_rate
    self.run()
    disk_io = psutil.disk_io_counters(False)
  File "/usr/lib/python3.8/site-packages/cherrypy/process/plugins.py", line 517,                                                                                                              in run
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in di                                                                                                             sk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in di                                                                                                             sk_io_counters
    self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/wok/plugins/gingerbase/model/host.py",                                                                                                              line 433, in update_host_stats
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in re                                                                                                             ad_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 277 207 7675 1311 3                                                                                                             4 0 176 873 0 226 2066 0 0 0 0 56 865\n'
    self._get_host_disk_io_rate(seconds)
  File "/usr/lib/python3.8/site-packages/wok/plugins/gingerbase/model/host.py",                                                                                                              line 474, in _get_host_disk_io_rate
    disk_io = psutil.disk_io_counters(False)
  File "/usr/lib64/python3.8/site-packages/psutil/__init__.py", line 2168, in di                                                                                                             sk_io_counters
    rawdict = _psplatform.disk_io_counters(**kwargs)
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1125, in di                                                                                                             sk_io_counters
    for entry in gen:
  File "/usr/lib64/python3.8/site-packages/psutil/_pslinux.py", line 1098, in re                                                                                                             ad_procfs
    raise ValueError("not sure how to interpret line %r" % line)
ValueError: not sure how to interpret line '   8       0 sda 277 207 7675 1311 3                                                                                                             4 0 176 873 0 226 2066 0 0 0 0 56 865\n'
libvirt: Domain Config erreur : metadata not found: Requested metadata element i                                                                                                             s not present
libvirt: Domain Config erreur : metadata not found: Requested metadata element i                                                                                                             s not present

Any Idea ? Is it due to python 3.8 ? May I shoud downgrade python ? 
Thanks.
Regards

**Comment by RhymeInspectah** [comment]
I've upgraded psutil. Now no errors after wokd launch in CLI but still nothing under host / dashboard tab in wok web UI.
