### ISSUE TITLE
Command to install depencency packages is removing python-cherrypy3 in Ubuntu

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#23]
The command provided on README.md to install the list of dependency packages on Debian/Ubuntu is automatically  removing the package python-cherrypy3, necessary to run wok:

```
test@ubuntu:~/wok$ sudo apt-get install gettext python-apt git python-configobj python-psutil sosreport python-lxml xsltproc python-parted python-cherrypy pep8 pyflakes python-requests g++ python-dev python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version.
gettext is already the newest version.
pep8 is already the newest version.
pyflakes is already the newest version.
python-dev is already the newest version.
python-lxml is already the newest version.
python-psutil is already the newest version.
python-requests is already the newest version.
xsltproc is already the newest version.
git is already the newest version.
python-pip is already the newest version.
The following packages were automatically installed and are no longer required:
  libjs-sphinxdoc libjs-underscore python-repoze.lru python-routes python-webob
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpython3.5-minimal libpython3.5-stdlib python-support python3.5 python3.5-minimal
Suggested packages:
  python-apt-dbg python-apt-doc python-configobj-doc python3.5-venv python3.5-doc
  binfmt-support
The following packages will be REMOVED:
  python-cherrypy3
The following NEW packages will be installed:
  libpython3.5-minimal libpython3.5-stdlib python-apt python-cherrypy python-configobj
  python-parted python-support python3.5 python3.5-minimal sosreport
0 upgraded, 10 newly installed, 1 to remove and 57 not upgraded.
Need to get 4,929 kB of archives.
After this operation, 2,537 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://br.archive.ubuntu.com/ubuntu/ wily/main libpython3.5-minimal amd64 3.5.0-3 [521 kB]
Get:2 http://br.archive.ubuntu.com/ubuntu/ wily/main python3.5-minimal amd64 3.5.0-3 [1,555 kB]
Get:3 http://br.archive.ubuntu.com/ubuntu/ wily/main libpython3.5-stdlib amd64 3.5.0-3 [2,137 kB]
Get:4 http://br.archive.ubuntu.com/ubuntu/ wily-updates/main python-apt amd64 1.0.1ubuntu0.1 [143 kB]
Get:5 http://br.archive.ubuntu.com/ubuntu/ wily/universe python-support all 1.0.15 [26.7 kB]
Get:6 http://br.archive.ubuntu.com/ubuntu/ wily/universe python-cherrypy all 2.3.0-4 [214 kB]
Get:7 http://br.archive.ubuntu.com/ubuntu/ wily/main python-configobj all 5.0.6-2 [34.2 kB]
Get:8 http://br.archive.ubuntu.com/ubuntu/ wily/universe python-parted amd64 3.10.5-1build1 [69.5 kB]
Get:9 http://br.archive.ubuntu.com/ubuntu/ wily/main python3.5 amd64 3.5.0-3 [150 kB]
Get:10 http://br.archive.ubuntu.com/ubuntu/ wily-updates/main sosreport amd64 3.2-2ubuntu1.1 [79.2 kB]
Fetched 4,929 kB in 3s (1,368 kB/s)
(Reading database ... 145815 files and directories currently installed.)
Removing python-cherrypy3 (3.5.0-2build1) ...
Processing triggers for man-db (2.7.4-1) ...
Selecting previously unselected package libpython3.5-minimal:amd64.
(Reading database ... 145018 files and directories currently installed.)
Preparing to unpack .../libpython3.5-minimal_3.5.0-3_amd64.deb ...
Unpacking libpython3.5-minimal:amd64 (3.5.0-3) ...
Selecting previously unselected package python3.5-minimal.
Preparing to unpack .../python3.5-minimal_3.5.0-3_amd64.deb ...
Unpacking python3.5-minimal (3.5.0-3) ...
Selecting previously unselected package libpython3.5-stdlib:amd64.
Preparing to unpack .../libpython3.5-stdlib_3.5.0-3_amd64.deb ...
Unpacking libpython3.5-stdlib:amd64 (3.5.0-3) ...
Selecting previously unselected package python-apt.
Preparing to unpack .../python-apt_1.0.1ubuntu0.1_amd64.deb ...
Unpacking python-apt (1.0.1ubuntu0.1) ...
Selecting previously unselected package python-support.
Preparing to unpack .../python-support_1.0.15_all.deb ...
Unpacking python-support (1.0.15) ...
Selecting previously unselected package python-cherrypy.
Preparing to unpack .../python-cherrypy_2.3.0-4_all.deb ...
Unpacking python-cherrypy (2.3.0-4) ...
Selecting previously unselected package python-configobj.
Preparing to unpack .../python-configobj_5.0.6-2_all.deb ...
Unpacking python-configobj (5.0.6-2) ...
Selecting previously unselected package python-parted.
Preparing to unpack .../python-parted_3.10.5-1build1_amd64.deb ...
Unpacking python-parted (3.10.5-1build1) ...
Selecting previously unselected package python3.5.
Preparing to unpack .../python3.5_3.5.0-3_amd64.deb ...
Unpacking python3.5 (3.5.0-3) ...
Selecting previously unselected package sosreport.
Preparing to unpack .../sosreport_3.2-2ubuntu1.1_amd64.deb ...
Unpacking sosreport (3.2-2ubuntu1.1) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Setting up libpython3.5-minimal:amd64 (3.5.0-3) ...
Setting up python3.5-minimal (3.5.0-3) ...
Setting up libpython3.5-stdlib:amd64 (3.5.0-3) ...
Setting up python-apt (1.0.1ubuntu0.1) ...
Setting up python-support (1.0.15) ...
Setting up python-cherrypy (2.3.0-4) ...
Setting up python-configobj (5.0.6-2) ...
Setting up python-parted (3.10.5-1build1) ...
Setting up python3.5 (3.5.0-3) ...
Setting up sosreport (3.2-2ubuntu1.1) ...
Processing triggers for python-support (1.0.15) ...
test@ubuntu:~/wok$ 
test@ubuntu:~/wok$ 
test@ubuntu:~/wok$ 
test@ubuntu:~/wok$ sudo src/wokd --environment=developmentTraceback (most recent call last):
  File "src/wokd", line 30, in <module>
    import wok.server
  File "/home/test/wok/src/wok/server.py", line 28, in <module>
    from wok import auth
  File "/home/test/wok/src/wok/auth.py", line 38, in <module>
    from wok.utils import get_all_tabs, run_command
  File "/home/test/wok/src/wok/utils.py", line 33, in <module>
    from cherrypy.lib.reprconf import Parser
ImportError: No module named reprconf
```

How to reproduce:

```
$ git clone https://github.com/kimchi-project/wok.git
#
# install Wok dependencies
#
$ sudo apt-get install gcc make autoconf automake gettext git pkgconf python-cherrypy3 python-cheetah python-imaging python-pam python-m2crypto python-jsonschema python-psutil python-ldap python-lxml nginx xsltproc openssl fonts-font-awesome texlive-fonts-extra pep8 pyflakes python-requests g++ python-dev python-pip
$ sudo pip install cython libsass
$ ./autogen.sh --system
$ make
$ sudo src/wokd --environment=development          # It works
#
# Ctrl-C to go back to console
# install GingerBase dependencies
# 
$ sudo apt-get install gettext python-apt git python-configobj python-psutil sosreport python-lxml xsltproc python-parted python-cherrypy pep8 pyflakes python-requests g++ python-dev python-pip
$ sudo src/wokd --environment=development
Traceback (most recent call last):
  File "src/wokd", line 30, in <module>
    import wok.server
  File "/home/test/wok/src/wok/server.py", line 28, in <module>
    from wok import auth
  File "/home/test/wok/src/wok/auth.py", line 38, in <module>
    from wok.utils import get_all_tabs, run_command
  File "/home/test/wok/src/wok/utils.py", line 33, in <module>
    from cherrypy.lib.reprconf import Parser
ImportError: No module named reprconf
```

Tested on a Ubuntu 15.10 machine.

**Comment by danielhb** [comment]
This is happening because the command is installing the CherryPy version 2, replacing the version 3 that WoK installed.

Anyway, I've accepted that the plug-ins will not be built independently (I'll update  #17 accordingly) because everything is too tied up with WoK (unit tests, for example).

In this scenario, there is absolutely no need for gingerbase to have python-cherrypy (or even python-cherrypy3) as dependency. If it's listed as WoK dependency, shouldn't  be listed in Gingerbase.

The solution here is to exclude _all_ packages listed in Gingerbase README that are listed in WoK README and add a 'building from source info' section to explain that the user will need the source code of WoK, either by using the submodules strategy or by individual cloning.

**Comment by danielhb** [comment]
Fixed upstream. Thanks!
